# Generated by Django 3.1.5 on 2021-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
