# Generated by Django 3.1.5 on 2021-03-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_savednewsitem_profile'),
        ('users', '0002_profile_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_news_items',
            field=models.ManyToManyField(to='feed.SavedNewsItem'),
        ),
    ]
