# Generated by Django 3.1.5 on 2021-03-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savednewsitem',
            name='profile',
        ),
    ]
